apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    app: payment
    purpose: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: payment
    spec:
      tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "roboshop"
          effect: "PreferNoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - payment
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: payment
          image: 826334059644.dkr.ecr.us-east-1.amazonaws.com/roboshop-payment-demo:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          env:
            - name: CART_HOST
              value: cart
            - name: USER_HOST
              value: user
            - name: AMQP_HOST
              value: rabbitmq
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq
            - name: AMQP_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq

